### ISSUE TITLE
What is the method used for?

### ISSUE THREAD

**Issue by jetaggart** [idknox/rantly#2]
https://github.com/idknox/rantly/blob/master/app/controllers/dashboard_controller.rb#L6

**Comment by idknox** [comment]
Sends the image over to the view for rendering - the action is the path for the img_tag

**Comment by idknox** [comment]
wow why'd you close my issue, I'm still working on it!

**Comment by jetaggart** [comment]
Haha, I bet. Did you ever figure out what that method is used for?

**Comment by idknox** [comment]
Apparently I passed this action's path helper as the first arg to every image_tag helper. Jesus. 2014 Ian is bad and should feel bad.
